// Generated by `vigil export`. Do not edit by hand.
// scenario: export.all-steps
// version: 3
// title: 모든 스텝 타입 — it's a 'quote' test
// env: stg (https://stg.example.com)
// The vigil YAML DSL is canonical; this Playwright spec is a derived export. Change the YAML and re-run `vigil export`.
import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL ?? 'https://stg.example.com';

// first number in a displayed value (thousands separators and units ignored), as vigil compares it
const firstNumber = (s: string): number => Number((s.replace(/[,\s\u00a0]/g, '').match(/[-+]?(\d+(\.\d+)?|\.\d+)([eE][-+]?\d+)?/) ?? [NaN])[0]);

test('export.all-steps: 모든 스텝 타입 — it\'s a \'quote\' test', async ({ page, context }) => {
  const consoleErrors: string[] = [];
  page.on('console', (msg) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  const http5xx: string[] = [];
  const http4xx: string[] = [];
  const http4xxOn = ['/api/', '/viewer-api/'];
  page.on('response', (res) => {
    const status = res.status();
    if (status >= 500) http5xx.push(`${status} ${res.request().method()} ${res.url()}`);
    if (status >= 400 && status < 500 && http4xxOn.some((u) => res.url().includes(u))) http4xx.push(`${status} ${res.request().method()} ${res.url()}`);
  });
  let active = page; // expect_popup switches the active page

  // step 1: 로그인 페이지 (flow login-as-student)
  await active.goto(BASE_URL + '/login');
  // step 2: fill (flow login-as-student)
  // label locator: getByPlaceholder is the fallback because vigil also matches placeholder text
  await active.getByLabel('아이디').or(active.getByPlaceholder('아이디')).fill('student01');
  // step 3: fill (flow login-as-student)
  // label locator: getByPlaceholder is the fallback because vigil also matches placeholder text
  await active.getByLabel('비밀번호').or(active.getByPlaceholder('비밀번호')).fill('pw');
  // step 4: click (flow login-as-student)
  const resp5 = active.waitForResponse((res) => res.url().includes('/api/login') && res.status() === 200); // step 5
  await active.getByRole('button', { name: '로그인' }).click();
  // step 5: assert_request (flow login-as-student)
  await resp5;
  // step 6: 대시보드 열기
  await active.goto(BASE_URL + '/dashboard?tab=1');
  // step 7: 강좌 카드 대기
  await expect(active.getByTestId('course-card')).toBeVisible({ timeout: 10000 });
  // step 8: click
  await active.getByRole('button', { name: '열기', exact: true }).click();
  // step 9: hover
  await active.locator('nav > a.menu').hover();
  // step 10: fill
  // label locator: getByPlaceholder is the fallback because vigil also matches placeholder text
  await active.getByLabel('검색어').or(active.getByPlaceholder('검색어')).fill('it\'s "quoted"\nnext');
  // step 11: type
  await active.locator('#search-input').pressSequentially('abc');
  // step 12: press
  await active.keyboard.press('Enter');
  // step 13: select
  const resp24 = active.waitForResponse((res) => res.url().includes('/api/courses') && res.request().method() === 'POST' && res.status() === 200, { timeout: 8000 }); // step 24
  const resp25 = active.waitForResponse((res) => res.url().includes('/api/list') && res.status() >= 200 && res.status() <= 299); // step 25
  await active.locator('select#grade').selectOption('3');
  // step 14: wait_ms
  await active.waitForTimeout(500);
  // step 15: wait_url
  await expect(active).toHaveURL(new RegExp("/courses\\?x=1"), { timeout: 5000 });
  // step 16: assert_url
  await expect(active).toHaveURL(new RegExp("^https://.*/courses/[0-9]+$"));
  // step 17: assert_text
  await expect(active.locator('body')).toContainText('총 3건');
  // step 18: assert_text
  await expect(active.getByTestId('title')).toHaveText('제목');
  // step 19: assert_no_text
  await expect(active.locator('body')).not.toContainText('오류가 발생');
  // step 20: assert_visible
  await expect(active.getByText('학습 시작', { exact: true }).nth(1)).toBeVisible();
  // step 21: assert_not_visible
  await expect(active.locator('a[href*="/logout"]')).not.toBeVisible();
  // step 22: assert_count
  await expect(active.locator('li.item')).toHaveCount(3);
  // step 23: assert_count
  await expect.poll(() => active.locator('li.item').count(), { timeout: 3000 }).toBeGreaterThanOrEqual(1);
  await expect.poll(() => active.locator('li.item').count(), { timeout: 3000 }).toBeLessThanOrEqual(5);
  // step 24: assert_request
  await resp24;
  // step 25: assert_request
  const res25 = await resp25;
  expect(await res25.text()).toContain('"ok":true');
  // step 26: assert_attr
  await expect(active.locator('a.next')).toHaveAttribute('href', new RegExp("page=2"));
  // step 27: assert_attr
  await expect(active.locator('input.agree')).toHaveAttribute('checked');
  // step 28: assert_attr
  await expect(active.getByTestId('badge')).toHaveAttribute('data-state', 'done');
  // step 29: 새 탭 열기
  const popup30 = context.waitForEvent('page', { timeout: 5000 }); // step 30
  await active.getByText('새 창').click();
  // step 30: expect_popup
  active = await popup30;
  await active.waitForLoadState();
  await expect(active).toHaveURL(new RegExp("/popup"), { timeout: 5000 });
  // step 31: eval
  const eval31 = await active.evaluate('document.title');
  expect(eval31).toEqual("학습관");
  // step 32: eval
  const eval32 = await active.evaluate('({ n: document.querySelectorAll(\'li\').length })');
  expect(eval32).toEqual({"n":3});
  // step 33: eval
  const resp35 = active.waitForResponse((res) => res.url().includes('/api/summary') && res.request().method() === 'GET'); // step 35
  const resp36 = active.waitForResponse((res) => res.url().includes('/api/summary')); // step 36
  const resp37 = active.waitForResponse((res) => res.url().includes('/api/summary')); // step 37
  await active.evaluate('window.scrollTo(0, 0)');
  // step 34: screenshot
  await active.screenshot({ path: test.info().outputPath('final.png'), fullPage: true });
  // step 35: assert_data
  const body35: any = await (await resp35).json();
  const api35: unknown = body35?.['data']?.['items']?.[0]?.['count'];
  const apiText35 = api35 == null ? '' : typeof api35 === 'object' ? JSON.stringify(api35) : String(api35);
  let ui35 = (await active.getByTestId('total-count').innerText()).trim();
  const match35 = ui35.match(new RegExp("총\\s*([0-9,]+)건"));
  expect(match35, 'ui_regex must match').not.toBeNull();
  ui35 = match35![1] ?? match35![0];
  expect(firstNumber(ui35)).toBeCloseTo(firstNumber(apiText35), 9);
  // step 36: assert_data
  const body36: any = await (await resp36).json();
  const api36: unknown = body36?.['data']?.['full name'];
  const apiText36 = api36 == null ? '' : typeof api36 === 'object' ? JSON.stringify(api36) : String(api36);
  const ui36 = (await active.locator('.name').innerText()).trim();
  expect(ui36.trim()).toBe(apiText36.trim());
  // step 37: assert_data
  const body37: any = await (await resp37).json();
  const api37: unknown = body37?.['data']?.['items']?.[1]?.['desc'];
  const apiText37 = api37 == null ? '' : typeof api37 === 'object' ? JSON.stringify(api37) : String(api37);
  const ui37 = (await active.locator('.desc').innerText()).trim();
  expect(ui37).toContain(apiText37.trim());
  // step 38: click (flow select-course)
  await active.getByTestId('course-1').click();
  // step 39: wait_url (flow select-course)
  await expect(active).toHaveURL(new RegExp("/course/1"));
  // step 40: -
  // TODO test.fixme: unknown flow "missing-flow"
  // step 41: click
  // TODO test.fixme: role fancywidget is not an ARIA role known to getByRole; using a [role=...] css locator
  await active.locator('[role="fancywidget"]').filter({ hasText: '위젯' }).click();
  // step 42: click
  await active.locator('[id="weird id"]').click();
  // step 43: click
  // locator.by unset: vigil also tries #id and a css selector for this value
  await active.getByTestId('submit-btn').click();
  // step 44: click
  // TODO test.fixme: invalid timeout "bogus" ignored
  await active.locator('a').click();

  // scenario asserts
  expect(consoleErrors, 'no_uncaught_console_error').toEqual([]);
  expect(http5xx, 'no_http_5xx').toEqual([]);
  expect(http4xx, 'no_http_4xx_on').toEqual([]);
});
