package agent

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// CustomProviderExtension writes a pi extension that registers one
// OpenAI-compatible endpoint as a provider. vigil generates it instead of
// editing ~/.pi/agent/models.json, so the operator's own pi setup is untouched
// and the endpoint only exists for vigil's runs.
//
// The key is read by pi from envVar at request time; it is never written here.
func CustomProviderExtension(dir, providerID, model, baseURL, envVar string, images bool) (string, error) {
	if providerID == "" || model == "" || baseURL == "" || envVar == "" {
		return "", fmt.Errorf("agent: custom provider needs an id, a model, a base URL and a key variable")
	}
	input := []string{"text"}
	if images {
		input = append(input, "image")
	}
	spec := map[string]any{
		"name":    "vigil custom endpoint",
		"baseUrl": baseURL,
		"apiKey":  "$" + envVar,
		"api":     "openai-completions",
		// Many gateways and self-hosted servers reject the developer role and
		// reasoning_effort; pi falls back to a plain system message with these off.
		"compat": map[string]any{"supportsDeveloperRole": false, "supportsReasoningEffort": false},
		"models": []map[string]any{{
			"id": model, "name": model, "reasoning": false, "input": input,
			"cost":          map[string]float64{"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
			"contextWindow": 200000, "maxTokens": 32000,
		}},
	}
	id, err := json.Marshal(providerID)
	if err != nil {
		return "", err
	}
	body, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return "", err
	}
	src := "// Generated by vigil from the console's LLM settings. Do not edit.\n" +
		"export default function (pi) {\n  pi.registerProvider(" + string(id) + ", " + string(body) + ");\n}\n"
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "vigil-custom-provider.js")
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		return "", err
	}
	return path, nil
}
