package proof

import (
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"strconv"
	"strings"
	"syscall"
	"time"
	"vigil/internal/store"
)

type ownedBrowser struct {
	PID     int    `json:"pid"`
	Profile string `json:"profile"`
}

// Recovery never kills by name or port. A persisted PID must still contain the
// exact unique profile generated by this provider before it receives a signal.
func recoverBrowsers(ctx context.Context, st *store.Store) error {
	rows, e := st.DB().QueryContext(ctx, `SELECT key,value FROM scheduler_state WHERE key LIKE 'proof:browser:%'`)
	if e != nil {
		return e
	}
	type entry struct {
		key string
		b   ownedBrowser
	}
	var entries []entry
	for rows.Next() {
		var key, raw string
		if e = rows.Scan(&key, &raw); e != nil {
			rows.Close()
			return e
		}
		var b ownedBrowser
		if e = json.Unmarshal([]byte(raw), &b); e != nil {
			rows.Close()
			return e
		}
		entries = append(entries, entry{key, b})
	}
	rows.Close()
	for _, entry := range entries {
		b := entry.b
		if b.PID <= 1 || b.Profile == "" {
			return fmt.Errorf("invalid browser ownership journal")
		}
		command, e := exec.CommandContext(ctx, "ps", "-p", strconv.Itoa(b.PID), "-o", "command=").Output()
		if e != nil && syscall.Kill(b.PID, 0) == nil {
			return fmt.Errorf("cannot inspect owned browser PID %d: %w", b.PID, e)
		}
		if e == nil && (strings.Contains(string(command), "--user-data-dir="+b.Profile+" ") || strings.HasSuffix(strings.TrimSpace(string(command)), "--user-data-dir="+b.Profile)) {
			if e = syscall.Kill(b.PID, syscall.SIGTERM); e != nil && e != syscall.ESRCH {
				return e
			}
			deadline := time.Now().Add(3 * time.Second)
			for syscall.Kill(b.PID, 0) == nil && time.Now().Before(deadline) {
				time.Sleep(20 * time.Millisecond)
			}
			if syscall.Kill(b.PID, 0) == nil {
				if e = syscall.Kill(b.PID, syscall.SIGKILL); e != nil && e != syscall.ESRCH {
					return e
				}
			}
		}
		if _, e = st.DB().ExecContext(ctx, `DELETE FROM scheduler_state WHERE key=?`, entry.key); e != nil {
			return e
		}
	}
	return nil
}
