// Package export turns a vigil scenario into other test formats. The YAML DSL
// stays canonical (SPEC WI-F): an export is derived output, never edited back.
package export

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	"vigil/internal/dsl"
)

// FormatPlaywright is the only supported export format.
const FormatPlaywright = "playwright"

// Formats lists the supported --format values.
var Formats = []string{FormatPlaywright}

// FileName returns the output file name of a scenario in a format.
func FileName(id, format string) (string, error) {
	switch format {
	case FormatPlaywright:
		return id + ".spec.ts", nil
	}
	return "", fmt.Errorf("unsupported export format %q (supported: %s)", format, strings.Join(Formats, ", "))
}

// Options parameterise one export.
type Options struct {
	Env     string               // environment name for the header
	BaseURL string               // default BASE_URL baked into the file
	Flows   map[string]*dsl.Flow // known flows for `uses` / use_flow expansion
}

// Playwright renders a scenario as a Playwright TypeScript spec.
func Playwright(sc *dsl.Scenario, o Options) []byte {
	g := &gen{sc: sc, o: o}
	g.steps = expand(sc, o.Flows)
	g.render()
	return []byte(g.b.String())
}

// step is one expanded step with its origin.
type step struct {
	dsl.Step
	flow string // flow id when the step came from a flow
	err  string // expansion problem (unknown flow, nested use_flow)
}

// expand inlines `uses` flows (before the steps) and inline use_flow steps.
func expand(sc *dsl.Scenario, flows map[string]*dsl.Flow) []step {
	var out []step
	inline := func(id string) {
		f := flows[id]
		if f == nil {
			out = append(out, step{err: fmt.Sprintf("unknown flow %q", id)})
			return
		}
		for _, st := range f.Steps {
			if st.UseFlow != "" {
				out = append(out, step{flow: id, err: fmt.Sprintf("nested use_flow %q in flow %q is not supported", st.UseFlow, id)})
				continue
			}
			out = append(out, step{Step: st, flow: id})
		}
	}
	for _, u := range sc.Uses {
		inline(u)
	}
	for _, st := range sc.Steps {
		if st.UseFlow != "" {
			inline(st.UseFlow)
			continue
		}
		out = append(out, step{Step: st})
	}
	return out
}

type gen struct {
	sc    *dsl.Scenario
	o     Options
	steps []step
	b     strings.Builder

	pv      string        // active page variable: page | active
	pending map[int][]int // action step index → later steps whose promise is armed before it
}

func (g *gen) line(format string, a ...any) {
	if len(a) > 0 {
		format = fmt.Sprintf(format, a...)
	}
	g.b.WriteString("  ")
	g.b.WriteString(format)
	g.b.WriteString("\n")
}

// isAction reports whether a step can trigger network / popup activity.
func isAction(k string) bool {
	switch k {
	case "goto", "click", "fill", "type", "press", "select", "hover", "eval":
		return true
	}
	return false
}

// needsPromise reports whether the step waits for something the preceding action triggers.
func needsPromise(k string) bool {
	return k == "assert_request" || k == "assert_data" || k == "expect_popup"
}

func (g *gen) render() {
	sc := g.sc
	g.pv = "page"
	g.pending = map[int][]int{}
	lastAction := -1
	hasPopup, hasNumber := false, false
	for i, st := range g.steps {
		k := st.Kind()
		if st.err == "" && isAction(k) {
			lastAction = i
		}
		if st.err == "" && needsPromise(k) && lastAction >= 0 {
			g.pending[lastAction] = append(g.pending[lastAction], i)
		}
		if k == "expect_popup" {
			hasPopup = true
		}
		if k == "assert_data" && st.AssertData.Compare == "number" {
			hasNumber = true
		}
	}
	if hasPopup {
		g.pv = "active"
	}

	title := oneLine(sc.Scenario.Title)
	g.b.WriteString("// Generated by `vigil export`. Do not edit by hand.\n")
	fmt.Fprintf(&g.b, "// scenario: %s\n// version: %d\n// title: %s\n// env: %s (%s)\n", sc.Scenario.ID, sc.Scenario.Version, title, orDash(g.o.Env), orDash(g.o.BaseURL))
	g.b.WriteString("// The vigil YAML DSL is canonical; this Playwright spec is a derived export. Change the YAML and re-run `vigil export`.\n")
	g.b.WriteString("import { test, expect } from '@playwright/test';\n\n")
	fmt.Fprintf(&g.b, "const BASE_URL = process.env.BASE_URL ?? %s;\n", tsString(g.o.BaseURL))
	if hasNumber {
		g.b.WriteString("\n// first number in a displayed value (thousands separators and units ignored), as vigil compares it\n")
		g.b.WriteString("const firstNumber = (s: string): number => Number((s.replace(/[,\\s\\u00a0]/g, '').match(/[-+]?(\\d+(\\.\\d+)?|\\.\\d+)([eE][-+]?\\d+)?/) ?? [NaN])[0]);\n")
	}
	g.b.WriteString("\n")
	name := sc.Scenario.ID
	if title != "" {
		name += ": " + title
	}
	fmt.Fprintf(&g.b, "test(%s, async ({ page, context }) => {\n", tsString(name))

	// scenario-level asserts become listeners armed before the first navigation
	a := sc.Assert
	if a.NoUncaughtConsoleError {
		g.line("const consoleErrors: string[] = [];")
		g.line("page.on('console', (msg) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });")
	}
	if a.NoHTTP5xx {
		g.line("const http5xx: string[] = [];")
	}
	if len(a.NoHTTP4xxOn) > 0 {
		g.line("const http4xx: string[] = [];")
		g.line("const http4xxOn = %s;", tsStringArray(a.NoHTTP4xxOn))
	}
	if a.NoHTTP5xx || len(a.NoHTTP4xxOn) > 0 {
		g.line("page.on('response', (res) => {")
		g.line("  const status = res.status();")
		if a.NoHTTP5xx {
			g.line("  if (status >= 500) http5xx.push(`${status} ${res.request().method()} ${res.url()}`);")
		}
		if len(a.NoHTTP4xxOn) > 0 {
			g.line("  if (status >= 400 && status < 500 && http4xxOn.some((u) => res.url().includes(u))) http4xx.push(`${status} ${res.request().method()} ${res.url()}`);")
		}
		g.line("});")
	}
	if hasPopup {
		g.line("let active = page; // expect_popup switches the active page")
	}
	if a.NoUncaughtConsoleError || a.NoHTTP5xx || len(a.NoHTTP4xxOn) > 0 || hasPopup {
		g.b.WriteString("\n")
	}

	for i := range g.steps {
		g.step(i)
	}

	if a.NoUncaughtConsoleError || a.NoHTTP5xx || len(a.NoHTTP4xxOn) > 0 {
		g.b.WriteString("\n")
		g.line("// scenario asserts")
	}
	if a.NoUncaughtConsoleError {
		g.line("expect(consoleErrors, 'no_uncaught_console_error').toEqual([]);")
	}
	if a.NoHTTP5xx {
		g.line("expect(http5xx, 'no_http_5xx').toEqual([]);")
	}
	if len(a.NoHTTP4xxOn) > 0 {
		g.line("expect(http4xx, 'no_http_4xx_on').toEqual([]);")
	}
	g.b.WriteString("});\n")
}

// promiseVar names the promise armed for a later step.
func promiseVar(kind string, i int) string {
	switch kind {
	case "expect_popup":
		return fmt.Sprintf("popup%d", i+1)
	}
	return fmt.Sprintf("resp%d", i+1)
}

func (g *gen) step(i int) {
	st := g.steps[i]
	k := st.Kind()
	label := st.Name
	if label == "" {
		label = k
	}
	if st.err != "" {
		g.line("// step %d: %s", i+1, orDash(label))
		g.line("// TODO test.fixme: %s", oneLine(st.err))
		return
	}
	if st.flow != "" {
		g.line("// step %d: %s (flow %s)", i+1, oneLine(label), st.flow)
	} else {
		g.line("// step %d: %s", i+1, oneLine(label))
	}
	// arm promises for the steps this action triggers
	for _, j := range g.pending[i] {
		g.arm(j)
	}
	switch k {
	case "goto":
		g.line("await %s.goto(%s);", g.pv, g.url(st.Goto))
	case "click":
		g.line("await %s.click(%s);", g.loc(st.Click), g.opts(st.Click.Timeout))
	case "hover":
		g.line("await %s.hover(%s);", g.loc(st.Hover), g.opts(st.Hover.Timeout))
	case "fill":
		g.line("await %s.fill(%s%s);", g.loc(&st.Fill.Locator), tsString(st.Fill.Input), g.optsArg(st.Fill.Timeout))
	case "type":
		g.line("await %s.pressSequentially(%s%s);", g.loc(&st.Type.Locator), tsString(st.Type.Input), g.optsArg(st.Type.Timeout))
	case "press":
		g.line("await %s.keyboard.press(%s);", g.pv, tsString(st.Press))
	case "select":
		g.line("await %s.selectOption(%s%s);", g.loc(&st.Select.Locator), tsString(st.Select.Option), g.optsArg(st.Select.Timeout))
	case "wait_for":
		g.line("await expect(%s).toBeVisible(%s);", g.loc(st.WaitFor), g.opts(st.WaitFor.Timeout))
	case "wait_ms":
		g.line("await %s.waitForTimeout(%d);", g.pv, st.WaitMs)
	case "wait_url", "assert_url":
		u := st.WaitURL
		if u == nil {
			u = st.AssertURL
		}
		g.line("await expect(%s).toHaveURL(%s%s);", g.pv, urlRegexp(u), g.optsArg(u.Timeout))
	case "assert_text", "assert_no_text":
		t, not := st.AssertText, ""
		if t == nil {
			t, not = st.AssertNoText, "not."
		}
		scope := g.pv + ".locator('body')"
		if t.In != nil {
			scope = g.loc(t.In)
		}
		m := "toContainText"
		if t.Exact {
			m = "toHaveText"
		}
		g.line("await expect(%s).%s%s(%s);", scope, not, m, tsString(t.Value))
	case "assert_visible":
		g.line("await expect(%s).toBeVisible(%s);", g.loc(st.AssertVisible), g.opts(st.AssertVisible.Timeout))
	case "assert_not_visible":
		g.line("await expect(%s).not.toBeVisible(%s);", g.loc(st.AssertNotVisible), g.opts(st.AssertNotVisible.Timeout))
	case "assert_count":
		c := st.AssertCount
		loc := g.loc(&c.Locator)
		if c.Equals != nil {
			g.line("await expect(%s).toHaveCount(%d%s);", loc, *c.Equals, g.optsArg(c.Timeout))
		}
		if c.Min != nil {
			g.line("await expect.poll(() => %s.count()%s).toBeGreaterThanOrEqual(%d);", loc, g.optsArg(c.Timeout), *c.Min)
		}
		if c.Max != nil {
			g.line("await expect.poll(() => %s.count()%s).toBeLessThanOrEqual(%d);", loc, g.optsArg(c.Timeout), *c.Max)
		}
	case "assert_request":
		g.assertRequest(i, st.AssertRequest)
	case "assert_attr":
		at := st.AssertAttr
		switch {
		case at.Equals != "":
			g.line("await expect(%s).toHaveAttribute(%s, %s);", g.loc(&at.Locator), tsString(at.Attr), tsString(at.Equals))
		case at.Contains != "":
			g.line("await expect(%s).toHaveAttribute(%s, %s);", g.loc(&at.Locator), tsString(at.Attr), tsRegexp(regexp.QuoteMeta(at.Contains)))
		default:
			g.line("await expect(%s).toHaveAttribute(%s);", g.loc(&at.Locator), tsString(at.Attr))
		}
	case "assert_data":
		g.assertData(i, st.AssertData)
	case "expect_popup":
		g.expectPopup(i, st.ExpectPopup)
	case "eval":
		e := st.Eval
		if e.Expect == "" {
			g.line("await %s.evaluate(%s);", g.pv, tsString(e.Script))
			return
		}
		v := fmt.Sprintf("eval%d", i+1)
		g.line("const %s = await %s.evaluate(%s);", v, g.pv, tsString(e.Script))
		var want any
		if err := json.Unmarshal([]byte(e.Expect), &want); err == nil {
			g.line("expect(%s).toEqual(%s);", v, jsLiteral(want))
		} else {
			g.line("expect(%s).toBe(%s);", v, tsString(e.Expect))
		}
	case "screenshot":
		name := st.Screenshot
		if !strings.HasSuffix(strings.ToLower(name), ".png") {
			name += ".png"
		}
		g.line("await %s.screenshot({ path: test.info().outputPath(%s), fullPage: true });", g.pv, tsString(name))
	default:
		g.line("// TODO test.fixme: unsupported step kind %q", k)
	}
}

// arm declares the promise a later step awaits, before the action that triggers it.
func (g *gen) arm(j int) {
	st := g.steps[j]
	switch st.Kind() {
	case "assert_request":
		g.line("const %s = %s.waitForResponse(%s%s); // step %d", promiseVar("assert_request", j), g.pv, requestPredicate(st.AssertRequest), g.optsArg(st.AssertRequest.Timeout), j+1)
	case "assert_data":
		d := st.AssertData
		g.line("const %s = %s.waitForResponse(%s); // step %d", promiseVar("assert_data", j), g.pv, requestPredicate(&dsl.RequestAssert{URLContains: d.API.URLContains, Method: d.API.Method}), j+1)
	case "expect_popup":
		g.line("const %s = context.waitForEvent('page'%s); // step %d", promiseVar("expect_popup", j), g.optsArg(st.ExpectPopup.Timeout), j+1)
	}
}

// awaitPromise returns the expression yielding the awaited value for step i, arming it
// inline when no preceding action exists.
func (g *gen) awaitPromise(i int, kind string) string {
	for _, js := range g.pending {
		for _, j := range js {
			if j == i {
				return "await " + promiseVar(kind, i)
			}
		}
	}
	return ""
}

func requestPredicate(a *dsl.RequestAssert) string {
	conds := []string{fmt.Sprintf("res.url().includes(%s)", tsString(a.URLContains))}
	if a.Method != "" {
		conds = append(conds, fmt.Sprintf("res.request().method() === %s", tsString(strings.ToUpper(a.Method))))
	}
	if a.Status != 0 {
		conds = append(conds, fmt.Sprintf("res.status() === %d", a.Status))
	}
	if a.StatusMin != 0 {
		conds = append(conds, fmt.Sprintf("res.status() >= %d", a.StatusMin))
	}
	if a.StatusMax != 0 {
		conds = append(conds, fmt.Sprintf("res.status() <= %d", a.StatusMax))
	}
	return "(res) => " + strings.Join(conds, " && ")
}

func (g *gen) assertRequest(i int, a *dsl.RequestAssert) {
	expr := g.awaitPromise(i, "assert_request")
	if expr == "" {
		expr = fmt.Sprintf("await %s.waitForResponse(%s%s)", g.pv, requestPredicate(a), g.optsArg(a.Timeout))
	}
	if a.BodyContains == "" {
		g.line("%s;", expr)
		return
	}
	v := fmt.Sprintf("res%d", i+1)
	g.line("const %s = %s;", v, expr)
	g.line("expect(await %s.text()).toContain(%s);", v, tsString(a.BodyContains))
}

func (g *gen) assertData(i int, d *dsl.DataAssert) {
	n := i + 1
	expr := g.awaitPromise(i, "assert_data")
	if expr == "" {
		expr = fmt.Sprintf("await %s.waitForResponse(%s)", g.pv, requestPredicate(&dsl.RequestAssert{URLContains: d.API.URLContains, Method: d.API.Method}))
	}
	g.line("const body%d: any = await (%s).json();", n, expr)
	path, err := jsonPathExpr(fmt.Sprintf("body%d", n), d.API.JSONPath)
	if err != nil {
		g.line("// TODO test.fixme: assert_data json_path %s: %s", oneLine(d.API.JSONPath), oneLine(err.Error()))
		return
	}
	g.line("const api%d: unknown = %s;", n, path)
	g.line("const apiText%d = api%d == null ? '' : typeof api%d === 'object' ? JSON.stringify(api%d) : String(api%d);", n, n, n, n, n)
	decl := "const"
	if d.UIRegex != "" {
		decl = "let"
	}
	g.line("%s ui%d = (await %s.innerText()).trim();", decl, n, g.loc(&d.UI))
	if d.UIRegex != "" {
		g.line("const match%d = ui%d.match(%s);", n, n, tsRegexp(d.UIRegex))
		g.line("expect(match%d, 'ui_regex must match').not.toBeNull();", n)
		g.line("ui%d = match%d![1] ?? match%d![0];", n, n, n)
	}
	switch d.Compare {
	case "text":
		g.line("expect(ui%d.trim()).toBe(apiText%d.trim());", n, n)
	case "number":
		g.line("expect(firstNumber(ui%d)).toBeCloseTo(firstNumber(apiText%d), 9);", n, n)
	case "contains":
		g.line("expect(ui%d).toContain(apiText%d.trim());", n, n)
	default:
		g.line("// TODO test.fixme: assert_data compare %q unsupported", d.Compare)
	}
}

func (g *gen) expectPopup(i int, p *dsl.PopupArgs) {
	expr := g.awaitPromise(i, "expect_popup")
	if expr == "" {
		expr = fmt.Sprintf("await context.waitForEvent('page'%s)", g.optsArg(p.Timeout))
	}
	g.line("active = %s;", expr)
	g.line("await active.waitForLoadState();")
	if p.URLContains != "" {
		g.line("await expect(active).toHaveURL(%s%s);", tsRegexp(regexp.QuoteMeta(p.URLContains)), g.optsArg(p.Timeout))
	}
}

// ---- locators --------------------------------------------------------------

// ariaRoles is the set Playwright's getByRole accepts; anything else falls back to
// a [role=...] CSS locator so the generated file stays valid TypeScript.
var ariaRoles = map[string]bool{}

func init() {
	for _, r := range strings.Fields(`alert alertdialog application article banner blockquote button caption cell checkbox code
		columnheader combobox complementary contentinfo definition deletion dialog directory document emphasis feed figure form
		generic grid gridcell group heading img insertion link list listbox listitem log main marquee math meter menu menubar
		menuitem menuitemcheckbox menuitemradio navigation none note option paragraph presentation progressbar radio radiogroup
		region row rowgroup rowheader scrollbar search searchbox separator slider spinbutton status strong subscript superscript
		switch tab table tablist tabpanel term textbox time timer toolbar tooltip tree treegrid treeitem`) {
		ariaRoles[r] = true
	}
}

var plainID = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]*$`)

// note writes a comment line before the statement being built.
func (g *gen) note(format string, a ...any) { g.line("// "+format, a...) }

// loc renders a locator expression on the active page; mapping caveats become a
// comment line above the statement.
func (g *gen) loc(l *dsl.Locator) string {
	s, note := Locator(g.pv, l)
	if note != "" {
		g.note("%s", note)
	}
	return s
}

// Locator renders a dsl locator as a Playwright locator chain on page variable pv.
// note is non-empty when the mapping is approximate or needs attention (TODO test.fixme).
func Locator(pv string, l *dsl.Locator) (s, note string) {
	if l == nil {
		return pv + ".locator('body')", "TODO test.fixme: locator missing"
	}
	by := l.By
	if by == "" {
		switch {
		case l.Role != "":
			by = "role"
		case l.Text != "":
			by = "text"
		case l.Name != "":
			by = "label"
		default:
			by = "test_id"
		}
	}
	switch by {
	case "test_id":
		s = fmt.Sprintf("%s.getByTestId(%s)", pv, tsString(l.Value))
		if l.By == "" {
			note = "locator.by unset: vigil also tries #id and a css selector for this value"
		}
	case "role":
		if ariaRoles[l.Role] {
			s = fmt.Sprintf("%s.getByRole(%s%s)", pv, tsString(l.Role), roleOpts(l))
		} else {
			s = fmt.Sprintf("%s.locator(%s)", pv, tsString(fmt.Sprintf(`[role=%s]`, cssString(l.Role))))
			if l.Name != "" {
				s += fmt.Sprintf(".filter({ hasText: %s })", tsString(l.Name))
			}
			note = "TODO test.fixme: role " + oneLine(l.Role) + " is not an ARIA role known to getByRole; using a [role=...] css locator"
		}
	case "label":
		name := first(l.Name, l.Text, l.Value)
		s = fmt.Sprintf("%s.getByLabel(%s%s).or(%s.getByPlaceholder(%s%s))", pv, tsString(name), exactOpt(l.Exact), pv, tsString(name), exactOpt(l.Exact))
		note = "label locator: getByPlaceholder is the fallback because vigil also matches placeholder text"
	case "id":
		if plainID.MatchString(l.Value) {
			s = fmt.Sprintf("%s.locator(%s)", pv, tsString("#"+l.Value))
		} else {
			s = fmt.Sprintf("%s.locator(%s)", pv, tsString("[id="+cssString(l.Value)+"]"))
		}
	case "text":
		s = fmt.Sprintf("%s.getByText(%s%s)", pv, tsString(first(l.Text, l.Value)), exactOpt(l.Exact))
	case "href":
		op := "*="
		if l.Exact {
			op = "="
		}
		s = fmt.Sprintf("%s.locator(%s)", pv, tsString("a[href"+op+cssString(l.Value)+"]"))
	case "css":
		s = fmt.Sprintf("%s.locator(%s)", pv, tsString(l.Value))
	default:
		s = pv + ".locator('body')"
		note = "TODO test.fixme: unknown locator by " + oneLine(l.By)
	}
	if l.Nth > 0 {
		s += fmt.Sprintf(".nth(%d)", l.Nth)
	}
	return s, note
}

func roleOpts(l *dsl.Locator) string {
	var parts []string
	if l.Name != "" {
		parts = append(parts, "name: "+tsString(l.Name))
	}
	if l.Exact {
		parts = append(parts, "exact: true")
	}
	if len(parts) == 0 {
		return ""
	}
	return ", { " + strings.Join(parts, ", ") + " }"
}

func exactOpt(exact bool) string {
	if exact {
		return ", { exact: true }"
	}
	return ""
}

func first(xs ...string) string {
	for _, x := range xs {
		if x != "" {
			return x
		}
	}
	return ""
}

// ---- options / timeouts --------------------------------------------------------

// timeoutMs parses a DSL duration; ok is false when unset or invalid.
func timeoutMs(raw string) (int64, bool) {
	if raw == "" {
		return 0, false
	}
	d, err := time.ParseDuration(raw)
	if err != nil || d <= 0 {
		return 0, false
	}
	return d.Milliseconds(), true
}

// opts renders `{ timeout: N }` or "" for a call with no other arguments.
func (g *gen) opts(raw string) string {
	if ms, ok := timeoutMs(raw); ok {
		return fmt.Sprintf("{ timeout: %d }", ms)
	}
	if raw != "" {
		g.note("TODO test.fixme: invalid timeout %q ignored", oneLine(raw))
	}
	return ""
}

// optsArg renders `, { timeout: N }` for a call that already has arguments.
func (g *gen) optsArg(raw string) string {
	if o := g.opts(raw); o != "" {
		return ", " + o
	}
	return ""
}

func (g *gen) url(u string) string {
	if strings.HasPrefix(u, "http://") || strings.HasPrefix(u, "https://") {
		return tsString(u)
	}
	return "BASE_URL + " + tsString(u)
}

func urlRegexp(u *dsl.URLAssert) string {
	if u.Matches != "" {
		return tsRegexp(u.Matches)
	}
	return tsRegexp(regexp.QuoteMeta(u.Contains))
}

// ---- json path ------------------------------------------------------------------

// jsonPathExpr converts the DSL json path ($, .key, [N], [*] first element,
// ["key"]) into an optional-chained TypeScript accessor on root.
func jsonPathExpr(root, path string) (string, error) {
	if !strings.HasPrefix(path, "$") {
		return "", fmt.Errorf("path must start with $")
	}
	rest := path[1:]
	var b strings.Builder
	b.WriteString(root)
	for len(rest) > 0 {
		switch rest[0] {
		case '.':
			end := strings.IndexAny(rest[1:], ".[")
			var name string
			if end < 0 {
				name, rest = rest[1:], ""
			} else {
				name, rest = rest[1:1+end], rest[1+end:]
			}
			if name == "" {
				return "", fmt.Errorf("empty key segment")
			}
			fmt.Fprintf(&b, "?.[%s]", tsString(name))
		case '[':
			end := strings.IndexByte(rest, ']')
			if end < 0 {
				return "", fmt.Errorf("unterminated [ in %q", rest)
			}
			inner := rest[1:end]
			rest = rest[end+1:]
			switch {
			case inner == "*":
				b.WriteString("?.[0]")
			case len(inner) >= 2 && (inner[0] == '"' || inner[0] == '\'') && inner[len(inner)-1] == inner[0]:
				fmt.Fprintf(&b, "?.[%s]", tsString(inner[1:len(inner)-1]))
			default:
				n, err := strconv.Atoi(inner)
				if err != nil || n < 0 {
					return "", fmt.Errorf("bad index [%s]", inner)
				}
				fmt.Fprintf(&b, "?.[%d]", n)
			}
		default:
			return "", fmt.Errorf("unexpected %q in path", rest)
		}
	}
	return b.String(), nil
}

// ---- escaping ------------------------------------------------------------------

// tsString renders s as a single-quoted TypeScript string literal.
func tsString(s string) string {
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '\'':
			b.WriteString(`\'`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\u2028', '\u2029': // line separators break JS literals
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\u%04x`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('\'')
	return b.String()
}

func tsStringArray(xs []string) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = tsString(x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// tsRegexp renders `new RegExp(<JSON string>)` so any pattern survives as-is.
func tsRegexp(pattern string) string {
	return "new RegExp(" + jsonString(pattern) + ")"
}

func jsonString(s string) string {
	return jsLiteral(s)
}

// jsLiteral renders a JSON-compatible value as a JavaScript literal (map keys sorted
// by encoding/json, so the output is deterministic).
func jsLiteral(v any) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return "null"
	}
	return strings.TrimRight(buf.String(), "\n")
}

// cssString renders s as a double-quoted CSS string (for attribute selectors).
func cssString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\a `).Replace(s) + `"`
}

// oneLine keeps comment text on one line and closes no comment early.
func oneLine(s string) string {
	s = strings.NewReplacer("\r\n", " ", "\n", " ", "\r", " ", "*/", "* /").Replace(s)
	return strings.TrimSpace(s)
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
